"""Add response_date column

Revision ID: a2fda66703a3
Revises: feae4f2bd0e4
Create Date: 2024-09-09 15:01:48.192193

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2fda66703a3'
down_revision = 'feae4f2bd0e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('response_date', sa.DateTime(), nullable=True))
        batch_op.alter_column('response',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.Text(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_response', schema=None) as batch_op:
        batch_op.alter_column('response',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=200),
               nullable=True)
        batch_op.drop_column('response_date')

    # ### end Alembic commands ###
