"""Add name column to TestResponse

Revision ID: feae4f2bd0e4
Revises: 
Create Date: 2024-09-09 14:42:15.162823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'feae4f2bd0e4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('email', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('age_group', sa.String(), nullable=True))
        batch_op.alter_column('response',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('test_response', schema=None) as batch_op:
        batch_op.alter_column('response',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('age_group')
        batch_op.drop_column('email')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
